### ISSUE TITLE
Bug when changing negative floating point number

### ISSUE THREAD

**Issue by stump26** [daangn/urlpack#13]
https://github.com/daangn/urlpack/blob/6593d09872497422adb92e4c886fb4d006a850ca/packages/msgpack/src/utils.ts?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L1

The isFloat function in the util file does not work if input is negative. So there is a problem that it is handled to incorrectly (Uint8Array(1) [ 255 ]) when changing negative floating point number.

**Comment by cometkim** [comment]
There is already a scheduled major change. It will be included in the v1 release.

Thanks for reporting this.
